version: "2.2"

services:
  fileservice:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    container_name: fileservice
    environment:
      DJANGO_CONFIGURATION: Development
    networks:
      - test-network

  fileservice_postgres:
    image: postgres:9.5
    container_name: postgres.fileservice
    volumes:
      - ./postgres/${CONTAINER_NAME}/data:/var/lib/postgresql/data
      - ./postgres/${CONTAINER_NAME}/conf:/etc/postgresql
      - ./postgres/${CONTAINER_NAME}/logs:/var/log/postgresql
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: fileservice
      POSTGRES_USER: fileservice
      POSTGRES_PASSWORD: fileservice

    networks:
      - test-network

networks:
  test-network:
    driver: bridge