# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-23 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20180523_1221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileExtension',
            new_name='FileExtensions',
        ),
        migrations.RenameField(
            model_name='fileextensions',
            old_name='available_extensions',
            new_name='allowed_extensions',
        ),
    ]
