# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-21 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20181128_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTemplate',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('filename_template', models.CharField(blank=True, max_length=128, null=True)),
                ('body_template', models.TextField()),
            ],
        ),
    ]
