# Generated by Django 3.0.3 on 2022-02-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_auto_20201116_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='ready',
            field=models.BooleanField(default=True, verbose_name='Ready'),
        ),
    ]
